### ISSUE TITLE
A* heuristics

### ISSUE THREAD

**Issue by enriko-riba** [jonghough/SharpGraph#7]
This is not a issue really but a question: how is the heuristics function in A* supposed to work on graphs? 
Unless the graph is organized into a fixed structure (e.g. grid) where one can calculate meaningful heuristics values, it is not possible to provide an estimate without having the solution already calculated. The tests are using constant values but this leads to suboptimal results or boils down to Dijkstra.

**Comment by jonghough** [comment]
Good point. I will add an example how to use a more "useful" A* heuristic.

**Comment by jonghough** [comment]
I added an additional unit test with a more complex A* example.

One way to handle more complex A* cases is to simply add a position to every node


And use a "Euclidean Distance" heuristic.
    
```
public class Position : NodeComponent
    {
        public float X;
        public float Y;

        public override void Copy(NodeComponent nodeComponent)
        {
            var pos = nodeComponent as Position;
            pos.X = this.X;
            pos.Y = this.Y;
        }

        public override bool Equals(object obj)
        {
            return base.Equals(obj);
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        public override string ToString()
        {
            return string.Format("{1}, {2}", this.X, this.Y);
        }
    }
    
   ...
   ...
 public class EuclideanHeuristic : IAStarHeuristic
    {
        private Graph graph;

        public EuclideanHeuristic(Graph graph)
        {
            this.graph = graph;
        }

        public float GetHeuristic(Node t, Node goal)
        {
            var posT = this.graph.GetComponent<Position>(t);
            var posGoal = this.graph.GetComponent<Position>(goal);

            return (float)
                Math.Sqrt(
                    ((posT.X - posGoal.X) * (posT.X - posGoal.X))
                        + ((posT.Y - posGoal.Y) * (posT.Y - posGoal.Y))
                );
        }
    }
```

**Comment by enriko-riba** [comment]
Thanks for the response. Unfortunately this is not applicable to most graph problems, but is a valid option if additional information like the position is available.
